#!/bin/sh
# '#%' starts a shell-line
# '#%include file' 
# '#slurp' at a line's end removes newline

FILE="$1"

IFS=
while read -r 'LINE'; do  
  if printf "%s" "$LINE" | grep -q "^#%include "; then
    ./tinytpl "$( printf "%s" "$LINE" | sed s/"^#%include "//  )"
    continue
  elif printf "%s" "$LINE" | grep -q "^#%"; then
    printf "%s\n" "$( printf "%s" "$LINE" | sed s/"^#%"// )"
    continue
  fi

  # dangerous signs are:  \, ", $(, ´ 
  LINE="$( printf "%s" "$LINE" | sed s/"\\\\"/"\\\\\\\\"/g | \
                                 sed s/'"'/'\\"'/g | \
                                 sed s/'$('/'\\$('/g | \
                                 sed s/'`'/'\\`'/g )"

  if printf "%s" "$LINE" | grep -q "#slurp$"; then
    LINE="$( printf "%s" "$LINE" | sed s/"#slurp$"// )"
    printf "%s\n" "printf \"%s\" \"$LINE\""
  else 
    printf "%s\n" "printf \"%s\\n\" \"$LINE\""
  fi
done < "$FILE"
