#!/bin/sh

file="$1"

IFS=
while read -r 'line'; do  
  if printf "%s" "$line" | grep "^#%include " >/dev/null; then
    ./tinytpl "$( printf "%s" "$line" | sed s/"^#%include "//  )"
    continue
  elif printf "%s" "$line" | grep "^#%" >/dev/null; then
    printf "%s\n" "$( printf "%s" "$line" | sed s/"^#%"// )"
    continue
  fi

  # dangerous signs are:  \, ", $(, ´ 
  line="$( printf "%s" "$line" | sed s/"\\\\"/"\\\\\\\\"/g | \
                                 sed s/'"'/'\\"'/g | \
                                 sed s/'$('/'\\$('/g | \
                                 sed s/'`'/'\\`'/g )"

  if printf "%s" "$line" | grep "#slurp$" >/dev/null; then
    line="`printf "%s" "$line" | sed s/"#slurp$"//`"
    printf "%s\n" "printf \"%s\" \"$line\""
  else 
    printf "%s\n" "printf \"%s\\n\" \"$line\""
  fi
done < "$file"
